console.log("Hello World")
console.log(document.body)
console.log(document.body.childNodes)
console.log(document.body.childNodes[1])
console.log(document.body.childNodes[1].childNodes)
let cont = document.body.childNodes[1]
console.log("let cont = document.body.childNodes[1]")
console.log(cont.firstElementChild)
console.log(cont.firstElementChild.style.color = "red")
console.log(cont.lastElementChild.style.backgroundColor = "red")
console.log(document.body.firstElementChild.childNodes[3].parentElement)
console.log(document.body.children)
console.log(document.body.children[1])
console.log(document.body.children[1].rows)